language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "wP8zcwC9wwFYpLgtjW4wsLTSh+ZHCZsr12ZMAWIMGvijKmZL/lU9/81m6fFpQintGSn2+pF1sMGCmNlZOaErWjkJmB9wlqesl08khu+o+AcJ6tISksfqj4vSzb6B81XjX13TjiLpCAtLNhzGMssCQPWhCuXFDevNxl5/euPpEWaUMQLQLJke4+q5uzQMuTJkKaoFTpocUTGHdXl8/gs5iD5Octf/VgPDvjIDHav14hkWOZ42VjnJ9ZQkQuQZ0nD0DDWbNpACf6KHVhHW4Y56RWzgpXdU0KlktBDecUWkqssz9iaJCZI17ow9av9PxKhEK6koJdylOPLEsUrkFVwVPLVF5in+PnfjmRJ6lodoWdMUKu7hqC8OkkGCqVqTwf164QkWWnC1ZveGEiytPdtFNv06a1nnE1HSJ395FovMrT0vK393NLy1zGLgnYjG9Wf3+YeAJ7KipQABCxqNl0wY3A5LVhSCxZ6MZXrtJrleQKSKHlZn951ULh68K4xfiGliIxoMzXW0hq/EvKcrUtrBV0MiXYmwOEkdrdiTF4c/4GHzQIfuggauxpqPDbWmRwP53NbbmjXRLXAdNEDFL4MshTMXEZYbZwVKOTFBP+biip/TAJqqCZlTd+R8XC+3gYzooTOCLpfjCrkRpJ+/VpUqnyunQXkuSLcRsFUZJFPaNTA="
