language: node_js
node_js:
- '6'
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
env:
  secure: "I1aT9u5/wn1gfmQq/pv/ET0EUCfgXtfYG/BNrsO1vuh/xo7dPNKYfcWqhXblrzEP33paUwqo9n9DFxlczPt4DdtVx5CLmUWO2KhJ+1tEgNfr/lAmYbZ556mT8qIrsLNE7SS9a4Fs2BC3rJQR8emA0VSb6q8Tq6/4SHH5NIh892BflucAGigxRhdtuNFfXGJsFt/OI7RcbrneYOT0nkbpQJONJcW0I2Kwu+3mMOt6/guZUt6dhz2HFERHEmnznhy7ecrJaxbSTv69VxQhcU00jZ1sObMNLNkZGkBl4nws9qXuij6dtFpEefjVD0DQg/8D7joKddegA9Gb845zuxjjWxX0V4WVhdq2nQoZy9/qVTioy555RwW+HOLVBq8qx+9D0ynDm7vdV2rYYI5mNcF58ldB53d9WatpVgh0tJ1Rsb4A3RhSVGOSPbCFWh4Ayzce9e7Y80rjANhuJsbGa7a89JIuJDzHUVHJp5gdEBhwYbvwSNwMdJWUUs5clmOGDuI8PvDJDQPnoS77HZBoQ/OPjV94CVHRYjHNZKg8DbZp/GqwxnpRIw1uxPxqSaYGJ3PHTbO5k26AMLuJqGJHzHE76sX+2Zd4uYKTUJ76MX+kSM4pAatgrBudQ3kPKAvmrYjHypEOlFHSxEKmiTL/+aPOLIsBwmFAUV6leWLh2eNFe/c="